### ISSUE TITLE
Petition link overlaps with and is blocked by copyright notice at the bottom

### ISSUE THREAD

**Issue by thefinn93** [UWave/uwave.fm#11]
Sorry for the huge screenshot, this was reported earlier today:
![screenshot](https://cloud.githubusercontent.com/assets/692970/7478641/ee6c1d20-f310-11e4-96c8-e2270204e16d.png)

@hasit wanna take this?

**Comment by hasit** [comment]
What browser is that? I use Firefox on my Android and it is perfect on mine.

**Comment by thefinn93** [comment]
Interesting. I'm using Chrome for Android and was able to reproduce it, I'm not sure what the original reporter was using (I've emailed her)

**Comment by hasit** [comment]
@thefinn93 cool. Let me know. 
Solution 1:
A way around that would be add the petition text to our foot.php. This would make it not overlap and would make it show up on every page.
Solution 2:
Add a !FLASH NEWS! section to index.php designated for one line news from now on.

**Comment by thefinn93** [comment]
eh, lets stick it in `foot.php`

**Comment by hasit** [comment]
@thefinn93 the foot approves

**Comment by hasit** [comment]
done. check on your mobile browsers and desktop browsers.

**Comment by thefinn93** [comment]
on desktop, it pushes the original foot text down off the edge of the screen... havent tested on mobile yet

**Comment by thefinn93** [comment]
On Chrome Mobile, it overlaps with the External Player link a little, but generally looks better:

![screenshot_2015-05-05-11-05-15](https://cloud.githubusercontent.com/assets/692970/7479509/fc0845b6-f316-11e4-8f5f-0d85d39882b9.png)

**Comment by hasit** [comment]
@thefinn93 chrome is so troublesome, imo. this would require a lot of restructuring. let's see what we can do.

**Comment by thefinn93** [comment]
Meh, this is pretty minor. I'm fine with closing this if you are.

**Comment by hasit** [comment]
done deal.
